package item

import "database/sql"

type TaxonItem struct {
	// ID is the identifier autogenerated by BHL database.
	ID uint

	// Vol contains not normalized volume field from BHl database.
	Vol string

	// YearStart contains the earliest year of publication. For journal volume
	// it would be a publication of the first journal issue, for a book it
	// would be the date of publication.
	YearStart sql.NullInt32

	// YearEnd contains the latest year of publication. The field is often
	// empty, if the Item was published at once.
	YearEnd sql.NullInt32

	// TitleID contains automatically generated id for the parent title of the
	// item.
	TitleID uint

	// TitleName is the name of a journal or a book.
	TitleName string

	// TaxonName of a requested taxon. It should be the main taxon of this
	// rank in the Item.
	TaxonName string

	// TaxonRanks rank associated with the TaxonName.
	TaxonRanks string

	// NamesNum is the number of unique names that have the rank.
	NamesNum int

	// TaxonPercentage is the percentage of the taxon compare to other
	// taxons of the same rank.
	TaxonPercentage int
}
