// Code generated by counterfeiter. DO NOT EDIT.
package reffindertest

import (
	"sync"

	"github.com/gnames/bhlnames/ent/input"
	"github.com/gnames/bhlnames/ent/namerefs"
	"github.com/gnames/bhlnames/ent/reffinder"
)

type FakeRefFinder struct {
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	ReferencesBHLStub        func(input.Input) (*namerefs.NameRefs, error)
	referencesBHLMutex       sync.RWMutex
	referencesBHLArgsForCall []struct {
		arg1 input.Input
	}
	referencesBHLReturns struct {
		result1 *namerefs.NameRefs
		result2 error
	}
	referencesBHLReturnsOnCall map[int]struct {
		result1 *namerefs.NameRefs
		result2 error
	}
	TitlesBHLStub        func(string) (map[int][]string, error)
	titlesBHLMutex       sync.RWMutex
	titlesBHLArgsForCall []struct {
		arg1 string
	}
	titlesBHLReturns struct {
		result1 map[int][]string
		result2 error
	}
	titlesBHLReturnsOnCall map[int]struct {
		result1 map[int][]string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRefFinder) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRefFinder) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeRefFinder) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeRefFinder) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRefFinder) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRefFinder) ReferencesBHL(arg1 input.Input) (*namerefs.NameRefs, error) {
	fake.referencesBHLMutex.Lock()
	ret, specificReturn := fake.referencesBHLReturnsOnCall[len(fake.referencesBHLArgsForCall)]
	fake.referencesBHLArgsForCall = append(fake.referencesBHLArgsForCall, struct {
		arg1 input.Input
	}{arg1})
	stub := fake.ReferencesBHLStub
	fakeReturns := fake.referencesBHLReturns
	fake.recordInvocation("ReferencesBHL", []interface{}{arg1})
	fake.referencesBHLMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRefFinder) ReferencesBHLCallCount() int {
	fake.referencesBHLMutex.RLock()
	defer fake.referencesBHLMutex.RUnlock()
	return len(fake.referencesBHLArgsForCall)
}

func (fake *FakeRefFinder) ReferencesBHLCalls(stub func(input.Input) (*namerefs.NameRefs, error)) {
	fake.referencesBHLMutex.Lock()
	defer fake.referencesBHLMutex.Unlock()
	fake.ReferencesBHLStub = stub
}

func (fake *FakeRefFinder) ReferencesBHLArgsForCall(i int) input.Input {
	fake.referencesBHLMutex.RLock()
	defer fake.referencesBHLMutex.RUnlock()
	argsForCall := fake.referencesBHLArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRefFinder) ReferencesBHLReturns(result1 *namerefs.NameRefs, result2 error) {
	fake.referencesBHLMutex.Lock()
	defer fake.referencesBHLMutex.Unlock()
	fake.ReferencesBHLStub = nil
	fake.referencesBHLReturns = struct {
		result1 *namerefs.NameRefs
		result2 error
	}{result1, result2}
}

func (fake *FakeRefFinder) ReferencesBHLReturnsOnCall(i int, result1 *namerefs.NameRefs, result2 error) {
	fake.referencesBHLMutex.Lock()
	defer fake.referencesBHLMutex.Unlock()
	fake.ReferencesBHLStub = nil
	if fake.referencesBHLReturnsOnCall == nil {
		fake.referencesBHLReturnsOnCall = make(map[int]struct {
			result1 *namerefs.NameRefs
			result2 error
		})
	}
	fake.referencesBHLReturnsOnCall[i] = struct {
		result1 *namerefs.NameRefs
		result2 error
	}{result1, result2}
}

func (fake *FakeRefFinder) TitlesBHL(arg1 string) (map[int][]string, error) {
	fake.titlesBHLMutex.Lock()
	ret, specificReturn := fake.titlesBHLReturnsOnCall[len(fake.titlesBHLArgsForCall)]
	fake.titlesBHLArgsForCall = append(fake.titlesBHLArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.TitlesBHLStub
	fakeReturns := fake.titlesBHLReturns
	fake.recordInvocation("TitlesBHL", []interface{}{arg1})
	fake.titlesBHLMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRefFinder) TitlesBHLCallCount() int {
	fake.titlesBHLMutex.RLock()
	defer fake.titlesBHLMutex.RUnlock()
	return len(fake.titlesBHLArgsForCall)
}

func (fake *FakeRefFinder) TitlesBHLCalls(stub func(string) (map[int][]string, error)) {
	fake.titlesBHLMutex.Lock()
	defer fake.titlesBHLMutex.Unlock()
	fake.TitlesBHLStub = stub
}

func (fake *FakeRefFinder) TitlesBHLArgsForCall(i int) string {
	fake.titlesBHLMutex.RLock()
	defer fake.titlesBHLMutex.RUnlock()
	argsForCall := fake.titlesBHLArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRefFinder) TitlesBHLReturns(result1 map[int][]string, result2 error) {
	fake.titlesBHLMutex.Lock()
	defer fake.titlesBHLMutex.Unlock()
	fake.TitlesBHLStub = nil
	fake.titlesBHLReturns = struct {
		result1 map[int][]string
		result2 error
	}{result1, result2}
}

func (fake *FakeRefFinder) TitlesBHLReturnsOnCall(i int, result1 map[int][]string, result2 error) {
	fake.titlesBHLMutex.Lock()
	defer fake.titlesBHLMutex.Unlock()
	fake.TitlesBHLStub = nil
	if fake.titlesBHLReturnsOnCall == nil {
		fake.titlesBHLReturnsOnCall = make(map[int]struct {
			result1 map[int][]string
			result2 error
		})
	}
	fake.titlesBHLReturnsOnCall[i] = struct {
		result1 map[int][]string
		result2 error
	}{result1, result2}
}

func (fake *FakeRefFinder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	fake.referencesBHLMutex.RLock()
	defer fake.referencesBHLMutex.RUnlock()
	fake.titlesBHLMutex.RLock()
	defer fake.titlesBHLMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRefFinder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ reffinder.RefFinder = new(FakeRefFinder)
