---

# BHL download URL
BHLDumpURL: https://www.biodiversitylibrary.org/data/data.zip

# gRPC URL for bhlindex service
BHLindexHost: bhlrpc.globalnames.org:80

# Path to keep downloaded data
InputDir: /tmp/bhlnames

# Postgresql host
DbHost: localhost

# Postgresql user
DbUser: postgres

# Postgresql password
DbPass:

# Postgresql database
DbName: bhlnames

# ProgressNum tells how many titles have to be processed before sending a
# progress report to the STDOUT. If the number is 0 reports do not generate.
ProgressNum: 10000
