// package namebhl provides interface to methods for
// collecting name data generated by BHLindex.
package namebhl

import "github.com/bits-and-blooms/bloom/v3"

// NameBHL interface provides methods to collect data from BHLindex.
type NameBHL interface {
	// ImportNames imports unique verified names from BHLindex.
	ImportNames() (*bloom.BloomFilter, error)
	
	// ImportOccurrences imports occurrences of names found by BHLindex.
	ImportOccurrences(*bloom.BloomFilter) error
}
